#!/usr/bin/bash

([[ -n $ZSH_EVAL_CONTEXT && $ZSH_EVAL_CONTEXT =~ :file$ ]] ||
 [[ -n $KSH_VERSION && $(cd "$(dirname -- "$0")" &&
    printf '%s' "${PWD%/}/")$(basename -- "$0") != "${.sh.file}" ]] ||
 [[ -n $BASH_VERSION ]] && (return 0 2>/dev/null)) && sourced=1 || sourced=0

if [ ${sourced} -eq 0 ]; then
  echo Do not execute this script, but rather source it in your shell config.
fi


p() {
  out="$(_p.py "$@")"
  exit_code=$?
  if [ ${exit_code} -eq 42 ]; then
    eval "$out"
    return $?
  else
    echo "$out"
    return ${exit_code}
  fi
}
